## Search algorithms within Optuna

In this notebook, I will demo how to select the search algorithm with Optuna. We will compare the use of:

- Grid Search 
- Randomized search
- Tree-structured Parzen Estimators
- CMA-ES


We can select the search algorithm from the [optuna.study.create_study()](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.create_study.html#optuna.study.create_study) class.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.ensemble import RandomForestClassifier

import optuna

g:\broswer download\udemy_courses\hyperparameter_optimization_for_ml\hyperparameter-optimization\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# load dataset

X, y = load_breast_cancer(return_X_y=True, as_frame=True)
y = y.map({0:1, 1:0})

X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
# the target:
# percentage of benign (0) and malign tumors (1)

y.value_counts() / len(y)

target
0    0.627417
1    0.372583
Name: count, dtype: float64

In [4]:
# split dataset into a train and test set

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((398, 30), (171, 30))

## Define the objective function

This is the hyperparameter response space, the function we want to minimize.

In [5]:
# the objective function takes the hyperparameter space
# as input

def objective(trial):

    rf_n_estimators = trial.suggest_int("rf_n_estimators", 100, 1000)
    rf_criterion = trial.suggest_categorical("rf_criterion", ['gini', 'entropy'])
    rf_max_depth = trial.suggest_int("rf_max_depth", 1, 4)
    rf_min_samples_split = trial.suggest_float("rf_min_samples_split", 0.01, 1)
    
    model = RandomForestClassifier(
        n_estimators=rf_n_estimators,
        criterion=rf_criterion,
        max_depth=rf_max_depth,
        min_samples_split=rf_min_samples_split,
    )

    score = cross_val_score(model, X_train, y_train, cv=3)
    accuracy = score.mean()
    return accuracy

## Randomized Search

[RandomSampler()](https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.RandomSampler.html)

In [6]:
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.RandomSampler(),
)


study.optimize(objective, n_trials=20)

[I 2026-08-27 00:03:05,846] A new study created in memory with name: no-name-97582cbe-c40a-4581-8382-041ee8002f7a
[I 2026-08-27 00:03:07,030] Trial 0 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 361, 'rf_criterion': 'gini', 'rf_max_depth': 4, 'rf_min_samples_split': 0.9123810249149172}. Best is trial 0 with value: 0.6256360598465861.
[I 2026-08-27 00:03:08,667] Trial 1 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 509, 'rf_criterion': 'gini', 'rf_max_depth': 4, 'rf_min_samples_split': 0.8573340570100346}. Best is trial 0 with value: 0.6256360598465861.
[I 2026-08-27 00:03:09,741] Trial 2 finished with value: 0.912128806865649 and parameters: {'rf_n_estimators': 259, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.6262504362238779}. Best is trial 2 with value: 0.912128806865649.
[I 2026-08-27 00:03:13,801] Trial 3 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 975, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.17142207947976795}. Best is trial 3 with value: 0.9171223513328776.
[I 2026-08-27 00:03:16,804] Trial 4 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 920, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.7699067629713713}. Best is trial 3 with value: 0.9171223513328776.
[I 2026-08-27 00:03:20,119] Trial 5 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 741, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1300668389982579}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:21,771] Trial 6 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 436, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.8592142450703472}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:23,885] Trial 7 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 606, 'rf_criterion': 'entropy', 'rf_max_depth': 4, 'rf_min_samples_split': 0.8321297674874195}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:25,082] Trial 8 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 300, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.5114328599623871}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:25,695] Trial 9 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 110, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.9387832172201395}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:27,728] Trial 10 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 514, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.796190595250103}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:28,629] Trial 11 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 252, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.8985631544650463}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:30,371] Trial 12 finished with value: 0.9346472241209084 and parameters: {'rf_n_estimators': 314, 'rf_criterion': 'entropy', 'rf_max_depth': 4, 'rf_min_samples_split': 0.25478191673971123}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:35,034] Trial 13 finished with value: 0.9371724766461608 and parameters: {'rf_n_estimators': 799, 'rf_criterion': 'entropy', 'rf_max_depth': 4, 'rf_min_samples_split': 0.21849375329331977}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:35,763] Trial 14 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 158, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.7258968700627488}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:37,453] Trial 15 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 507, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.6472625712371557}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:39,741] Trial 16 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 551, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.09441196238478951}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:41,328] Trial 17 finished with value: 0.9196476038581302 and parameters: {'rf_n_estimators': 331, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.37265277847178385}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:43,635] Trial 18 finished with value: 0.9271094402673349 and parameters: {'rf_n_estimators': 386, 'rf_criterion': 'gini', 'rf_max_depth': 4, 'rf_min_samples_split': 0.323347456521387}. Best is trial 5 with value: 0.9397357028935976.
[I 2026-08-27 00:03:44,538] Trial 19 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 261, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.7109811554190667}. Best is trial 5 with value: 0.9397357028935976.

In [7]:
study.best_params

{'rf_n_estimators': 741,
 'rf_criterion': 'entropy',
 'rf_max_depth': 2,
 'rf_min_samples_split': 0.1300668389982579}

In [8]:
study.best_value

0.9397357028935976

In [9]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_rf_criterion,params_rf_max_depth,params_rf_min_samples_split,params_rf_n_estimators,state
0,0,0.625636,2026-08-27 00:03:05.848904,2026-08-27 00:03:07.030183,0 days 00:00:01.181279,gini,4,0.912381,361,COMPLETE
1,1,0.625636,2026-08-27 00:03:07.031687,2026-08-27 00:03:08.667768,0 days 00:00:01.636081,gini,4,0.857334,509,COMPLETE
2,2,0.912129,2026-08-27 00:03:08.668768,2026-08-27 00:03:09.741625,0 days 00:00:01.072857,gini,2,0.626250,259,COMPLETE
3,3,0.917122,2026-08-27 00:03:09.743678,2026-08-27 00:03:13.801827,0 days 00:00:04.058149,gini,1,0.171422,975,COMPLETE
4,4,0.625636,2026-08-27 00:03:13.802348,2026-08-27 00:03:16.804373,0 days 00:00:03.002025,entropy,2,0.769907,920,COMPLETE
5,5,0.939736,2026-08-27 00:03:16.805372,2026-08-27 00:03:20.119413,0 days 00:00:03.314041,entropy,2,0.130067,741,COMPLETE
6,6,0.625636,2026-08-27 00:03:20.120415,2026-08-27 00:03:21.771334,0 days 00:00:01.650919,gini,2,0.859214,436,COMPLETE
7,7,0.625636,2026-08-27 00:03:21.773218,2026-08-27 00:03:23.885165,0 days 00:00:02.111947,entropy,4,0.832130,606,COMPLETE
8,8,0.917122,2026-08-27 00:03:23.886164,2026-08-27 00:03:25.082370,0 days 00:00:01.196206,entropy,2,0.511433,300,COMPLETE
9,9,0.625636,2026-08-27 00:03:25.084889,2026-08-27 00:03:25.695136,0 days 00:00:00.610247,entropy,3,0.938783,110,COMPLETE
10,10,0.625636,2026-08-27 00:03:25.697136,2026-08-27 00:03:27.728550,0 days 00:00:02.031414,gini,1,0.796191,514,COMPLETE
11,11,0.625636,2026-08-27 00:03:27.729548,2026-08-27 00:03:28.629931,0 days 00:00:00.900383,entropy,3,0.898563,252,COMPLETE
12,12,0.934647,2026-08-27 00:03:28.630942,2026-08-27 00:03:30.370541,0 days 00:00:01.739599,entropy,4,0.254782,314,COMPLETE
13,13,0.937172,2026-08-27 00:03:30.373066,2026-08-27 00:03:35.034393,0 days 00:00:04.661327,entropy,4,0.218494,799,COMPLETE
14,14,0.625636,2026-08-27 00:03:35.035392,2026-08-27 00:03:35.763518,0 days 00:00:00.728126,entropy,1,0.725897,158,COMPLETE
15,15,0.625636,2026-08-27 00:03:35.764686,2026-08-27 00:03:37.453838,0 days 00:00:01.689152,gini,2,0.647263,507,COMPLETE
16,16,0.939736,2026-08-27 00:03:37.455842,2026-08-27 00:03:39.741403,0 days 00:00:02.285561,gini,3,0.094412,551,COMPLETE
17,17,0.919648,2026-08-27 00:03:39.742415,2026-08-27 00:03:41.328329,0 days 00:00:01.585914,gini,1,0.372653,331,COMPLETE
18,18,0.927109,2026-08-27 00:03:41.329329,2026-08-27 00:03:43.635338,0 days 00:00:02.306009,gini,4,0.323347,386,COMPLETE
19,19,0.625636,2026-08-27 00:03:43.636337,2026-08-27 00:03:44.538555,0 days 00:00:00.902218,gini,2,0.710981,261,COMPLETE

## TPE

TPESampler is the default. You'll probably remember that for TPE, we first sample a few hyperparameter combinations at random, and then we start the sequential search, based on TPE with a certain kernel, and an acquisition function.

All these parameters are determined by default, but you can change them. More details in the [TPESampler()](https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.TPESampler.html) documentation.

In [10]:
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(
        # the number of initial points to sample at random before doing the sequential search
        n_startup_trials=10
    ),
)

study.optimize(objective, n_trials=20)

[I 2026-08-27 00:03:44,687] A new study created in memory with name: no-name-1f06efa6-a40d-45e6-a955-7add4a096998
[I 2026-08-27 00:03:46,385] Trial 0 finished with value: 0.9271853877117034 and parameters: {'rf_n_estimators': 377, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.45434547315577234}. Best is trial 0 with value: 0.9271853877117034.
[I 2026-08-27 00:03:47,008] Trial 1 finished with value: 0.9171413381939697 and parameters: {'rf_n_estimators': 152, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.4000176546706351}. Best is trial 0 with value: 0.9271853877117034.
[I 2026-08-27 00:03:49,314] Trial 2 finished with value: 0.9447482342219184 and parameters: {'rf_n_estimators': 501, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.08840676752084796}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:03:52,072] Trial 3 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 617, 'rf_criterion': 'gini', 'rf_max_depth': 4, 'rf_min_samples_split': 0.9955384220613194}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:03:54,214] Trial 4 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 452, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.9630857276695779}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:03:57,811] Trial 5 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 605, 'rf_criterion': 'gini', 'rf_max_depth': 4, 'rf_min_samples_split': 0.6545598309387737}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:03,265] Trial 6 finished with value: 0.9321409584567478 and parameters: {'rf_n_estimators': 691, 'rf_criterion': 'entropy', 'rf_max_depth': 4, 'rf_min_samples_split': 0.3011670931329534}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:06,603] Trial 7 finished with value: 0.9196476038581302 and parameters: {'rf_n_estimators': 713, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.39132688299240065}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:06,953] Trial 8 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 109, 'rf_criterion': 'entropy', 'rf_max_depth': 4, 'rf_min_samples_split': 0.6960316024596599}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:11,359] Trial 9 finished with value: 0.9221348826611985 and parameters: {'rf_n_estimators': 963, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.45942182179067875}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:16,274] Trial 10 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.07111745778040185}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:20,682] Trial 11 finished with value: 0.942241968557758 and parameters: {'rf_n_estimators': 997, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.06086911841212517}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:25,595] Trial 12 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 801, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.026661909444415433}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:27,651] Trial 13 finished with value: 0.942241968557758 and parameters: {'rf_n_estimators': 333, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1758433269493866}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:31,247] Trial 14 finished with value: 0.9397167160325055 and parameters: {'rf_n_estimators': 496, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1956951640447301}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:36,633] Trial 15 finished with value: 0.9221538695222905 and parameters: {'rf_n_estimators': 853, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.16293990827880295}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:38,894] Trial 16 finished with value: 0.9372294372294373 and parameters: {'rf_n_estimators': 300, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.027149284684593378}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:44,060] Trial 17 finished with value: 0.9346472241209084 and parameters: {'rf_n_estimators': 855, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.28922789757652223}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:46,295] Trial 18 finished with value: 0.924679122047543 and parameters: {'rf_n_estimators': 518, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.13694258519348923}. Best is trial 2 with value: 0.9447482342219184.
[I 2026-08-27 00:04:47,251] Trial 19 finished with value: 0.9346662109820004 and parameters: {'rf_n_estimators': 209, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.2663426113207802}. Best is trial 2 with value: 0.9447482342219184.

In [11]:
study.best_params

{'rf_n_estimators': 501,
 'rf_criterion': 'entropy',
 'rf_max_depth': 2,
 'rf_min_samples_split': 0.08840676752084796}

In [12]:
study.best_value

0.9447482342219184

## CMA-ES

CmaEsSampler

In [13]:
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.CmaEsSampler(),
)

study.optimize(objective, n_trials=5)

[I 2026-08-27 00:04:47,309] A new study created in memory with name: no-name-44658c20-d9df-4c2f-8d29-b42b98612eba
[I 2026-08-27 00:04:48,160] Trial 0 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 158, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.48611185505070753}. Best is trial 0 with value: 0.9171223513328776.
[W 2026-08-27 00:04:48,312] The parameter `rf_criterion` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-08-27 00:04:50,659] Trial 1 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 527, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.771010035618076}. Best is trial 0 with value: 0.9171223513328776.
[W 2026-08-27 00:04:50,661] The parameter `rf_criterion` in Trial#2 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-08-27 00:04:52,102] Trial 2 finished with value: 0.9346851978430926 and parameters: {'rf_n_estimators': 322, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.4255474818375359}. Best is trial 2 with value: 0.9346851978430926.
[W 2026-08-27 00:04:52,106] The parameter `rf_criterion` in Trial#3 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-08-27 00:04:57,636] Trial 3 finished with value: 0.9296157059314955 and parameters: {'rf_n_estimators': 762, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.32777046632685575}. Best is trial 2 with value: 0.9346851978430926.
[W 2026-08-27 00:04:57,638] The parameter `rf_criterion` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-08-27 00:04:58,852] Trial 4 finished with value: 0.9196286169970379 and parameters: {'rf_n_estimators': 333, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.46844045071979923}. Best is trial 2 with value: 0.9346851978430926.

In [14]:
study.best_params

{'rf_n_estimators': 322,
 'rf_criterion': 'gini',
 'rf_max_depth': 2,
 'rf_min_samples_split': 0.4255474818375359}

In [15]:
study.best_value

0.9346851978430926

## Grid Search

GridSampler()

We are probably not going to perform GridSearch with Optuna, but in case you wanted to, you need to add a variable with the space, with the exact values that you want to be tested.

In [16]:
search_space = {
    "rf_n_estimators": [100, 500, 1000],
    "rf_criterion": ['gini', 'entropy'],
    "rf_max_depth": [1, 2, 3],
    "rf_min_samples_split": [0.1, 1.0]
}

In [17]:
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.GridSampler(search_space),
)

study.optimize(objective)

[I 2026-08-27 00:04:58,920] A new study created in memory with name: no-name-5fc8e449-08b2-4d13-983b-a2d64205008f
[I 2026-08-27 00:05:01,511] Trial 0 finished with value: 0.9372294372294373 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 0 with value: 0.9372294372294373.
[I 2026-08-27 00:05:05,548] Trial 1 finished with value: 0.9146160856687172 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 0 with value: 0.9372294372294373.
[I 2026-08-27 00:05:07,560] Trial 2 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 0 with value: 0.9372294372294373.
[I 2026-08-27 00:05:08,052] Trial 3 finished with value: 0.942222981696666 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:09,655] Trial 4 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:09,982] Trial 5 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:11,860] Trial 6 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:15,362] Trial 7 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:18,539] Trial 8 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:21,640] Trial 9 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:21,976] Trial 10 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:25,148] Trial 11 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:25,469] Trial 12 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:27,184] Trial 13 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:31,717] Trial 14 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 3 with value: 0.942222981696666.
[I 2026-08-27 00:05:35,743] Trial 15 finished with value: 0.942241968557758 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:37,769] Trial 16 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:40,937] Trial 17 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:44,342] Trial 18 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:49,106] Trial 19 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:51,116] Trial 20 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:55,473] Trial 21 finished with value: 0.942241968557758 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:57,897] Trial 22 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:05:58,612] Trial 23 finished with value: 0.9397167160325055 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 3, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:01,095] Trial 24 finished with value: 0.9397357028935976 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:01,549] Trial 25 finished with value: 0.9396977291714134 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:01,970] Trial 26 finished with value: 0.9397167160325055 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:05,246] Trial 27 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 1000, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:08,308] Trial 28 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:08,827] Trial 29 finished with value: 0.9120528594212804 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:09,196] Trial 30 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:12,042] Trial 31 finished with value: 0.9171223513328776 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:12,693] Trial 32 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 2, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:15,694] Trial 33 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 500, 'rf_criterion': 'entropy', 'rf_max_depth': 3, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:16,132] Trial 34 finished with value: 0.6256360598465861 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 1.0}. Best is trial 15 with value: 0.942241968557758.
[I 2026-08-27 00:06:16,649] Trial 35 finished with value: 0.9196665907192223 and parameters: {'rf_n_estimators': 100, 'rf_criterion': 'gini', 'rf_max_depth': 1, 'rf_min_samples_split': 0.1}. Best is trial 15 with value: 0.942241968557758.

In [18]:
study.best_params

{'rf_n_estimators': 1000,
 'rf_criterion': 'gini',
 'rf_max_depth': 2,
 'rf_min_samples_split': 0.1}

In [19]:
study.best_value

0.942241968557758